on:  
  push:  
    branches: [ master ]
  
jobs:  
  build:  
  
    runs-on: ubuntu-latest  
  
    steps:  
    - name: Publish  
      uses: brandedoutcast/publish-nuget@v2.5.2  
      with:   
        PROJECT_FILE_PATH: BetterFloatMenu/BetterFloatMenu.csproj 
        NUGET_KEY: ${{secrets.NUGET_API}}
        INCLUDE_SYMBOLS: true
        PACKAGE_NAME: BetterFloatMenu        
