on:  
  push:  
    branches: [ master ]
  
env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true

jobs:  
  build:  
  
    runs-on: windows-latest
 
    steps:
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1
      
    - name: Restore NuGet Packages       
    - uses: actions/checkout@master
    - uses: nuget/setup-nuget@v1
      with:
        nuget-api-key: ${{secrets.NUGET_API}}
        nuget-version: '5.x'
    - run: nuget restore BetterFloatMenu.sln

    - name: Build app for release
      run: msbuild BetterFloatMenu\BetterFloatMenu.csproj -t:rebuild -verbosity:diag -property:Configuration=Release
      
    - name: Publish
      run: nuget push **\*.nupkg -Source 'https://api.nuget.org/v3/index.json' -ApiKey ${{secrets.NUGET_API}}
